### PR TITLE
touch styleguide before pl build

### PR DESCRIPTION
**Pull request by illepic**

### CODE REVIEW

**Comment by EvanLovely** [comment]
From @illepic :

> runs a `touch public/styleguide/html/styleguide.html` so we can actually build this thing without styleguide.html being commmitted to repo

**Comment by EvanLovely** [comment]
Getting an error on build:

    >> ReferenceError: serverPath is not defined

We'll want to use `config.plDir` instead. I swapped it out, and it ran fine. I then deleted the whole `pattern-lab/public/` directory and tried again and it failed because the folder's weren't there. So I'm putting in something like this:

            command: "mkdir -p " + config.plDir + "public/styleguide/html/ && touch " + config.plDir + "public/styleguide/html/styleguide.html && php " + config.plDir + "core/builder.php --generate --nocache"

I've pulled in your feature branch and my above fixes ( 5227de ) into a feature branch on this repo: feature-improve-public-folder

Next up is changing the `.gitignore` and pulling committed files in the `public/` folder out of the repo.

**Comment by EvanLovely** [comment]
I've pushed the above changes and tested a fresh install and am getting a style-less homepage. So we got something broken. To test:

```bash
git clone git@github.com:phase2/pattern-lab-starter.git --branch feature-improve-public-folder
npm install && bower install && bundle install
grunt
```

It's important to clone directly to this feature branch because if we clone from master or dev, then switch to the feature branch, we'll bring along the pre-created `public/` directory.

**Comment by illepic** [comment]
Gotcha, I tested on a pre-existing clone, not a first-run. I'll take another shot.

**Comment by illepic** [comment]
Also hadn't pulled in upstream. Fixes incoming.

**Comment by EvanLovely** [comment]
This has been taken care of now; closing PR.

**Pull request closed without merging**
