### PR TITLE
Create license

### PR DESCRIPTION
**Pull request by illepic**

### CODE REVIEW

**Comment by evanmwillhite** [comment]
Just noticed this - someone corrected me on [Emulsify](https://github.com/fourkitchens/emulsify/issues/89) for having an MIT license when it appears [anything that extends Drupal needs a GPL2 license](https://www.drupal.org/about/licensing#q7).

**Comment by illepic** [comment]
@evanmwillhite : Interesting. I'm learning about licensing here, but is the basic gist of this that any Drupal theme or module must be GPL2?

**Comment by grayside** [comment]
That's always been my understanding, but MIT is regarded as compatible so maybe you can dual license?

**Comment by illepic** [comment]
Noting here to update in package.json as well. @grayside, I guess we'll just go GPL2 and keep it simple?

**Pull request merged**
