### PR TITLE
Pointing Pattern Lab core deps to new and improved forked deps

### PR DESCRIPTION
**Pull request by EvanLovely**
This updates all the Pattern Lab dependencies to the forked variants being maintained by myself and others in the community in the [Drupal Pattern Lab org](https://github.com/drupal-pattern-lab). We'd love some contribution and help over there if any of you have time! I'm happy to get this in to PL Starter and hope to see the tools grow and evolve now that I'm gone from Phase2; good luck!

### CODE REVIEW

**Comment by illepic** [comment]
Very serious thanks for this dude here.

**Comment by geoff-winner** [comment]
Thanks Evan!

**Comment by illepic** [comment]
Digging up the chain of composer dependencies for what needs doctrine 1.5 which requires PHP 7.1 which causes builds to fail on PHP 5.6.

**Comment by illepic** [comment]
Blerp: grandchild dependency. Opened an issue at patternlab-php-core repo: https://github.com/drupal-pattern-lab/patternlab-php-core/issues/13.

**Comment by illepic** [comment]
Updating in package.json:

     "setup": "cd pattern-lab && composer install --no-interaction --ignore-platform-reqs",

gets around this for now.

**Pull request merged**
